pipeline{
  agent any
  stages{
    stage(test){
      agent{
        docker { image 'mvn:3.8.3-adoptopenjdk11-'}
      }
      steps{
      sh 'java --version'
      }
      stage(testb){
      agent{
        docker { image 'node:16-alpine'}
      }
      steps{
        sh 'node --version'
      }
      }
    }
  }
}

   