pipeline {
  agent any
  stages {
    stage('test') {
      agent {
        docker { image 'maven:3.8.3-eclipse-temurin-11' }
      }
      steps {
        sh 'java --version'
      }
    }

    stage('testb') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
